Added "Artificial Intelligence" and "Cybersecurity" to the typed words.
ugcompsoc/compsoc.ie pull request #31
Opened 2024-11-13 01:10 UTC by Laan33

Added "Artificial Intelligence" and "Cybersecurity" to the typed words.

Set the typing to finish on "Computer".
Further info - we have not enabled looping, this typing will go through the list, and then finish on "Computer Society".

<img width="776" alt="Screenshot 2024-11-13 at 01 10 28" src="https://github.com/user-attachments/assets/529afb39-05f7-4b46-9945-052650280a76">
<img width="789" alt="Screenshot 2024-11-13 at 01 10 23" src="https://github.com/user-attachments/assets/1feebb8c-d5ad-40ef-b63d-932aa3f9b3e5">

2024-11-13 01:12 UTC, Laan33 commented
I believe @Daxorinator is very passionate on this addition, so I would ask for @Daxorinator's review before merging.

2024-11-17 14:45 UTC, Daxorinator requested changes

2024-11-17 14:45 UTC, Daxorinator commented on src/components/splash/splash.component.tsx
> +            strings: ["Computer", "Developer", "Technology", "Artificial Intelligence", "Cybersecurity", "Computer"], // Strings to display
Computer listed twice? Does this loop, or does it stop at the end?

2024-11-17 14:46 UTC, Laan33 commented on src/components/splash/splash.component.tsx
> +            strings: ["Computer", "Developer", "Technology", "Artificial Intelligence", "Cybersecurity", "Computer"], // Strings to display
it stops on computer, see the description 🙏

2024-11-17 14:47 UTC, Daxorinator commented on src/components/splash/splash.component.tsx
> +            strings: ["Computer", "Developer", "Technology", "Artificial Intelligence", "Cybersecurity", "Computer"], // Strings to display
Resolved

2024-11-17 14:48 UTC, Daxorinator approved these changes

2024-11-17 14:48 UTC, merged